controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: true

    diff_cont: 
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diff_cont:
  ros__parameters:

    publish_rate: 50

    base_frame_id: base_link

    left_wheel_names: ['Revolute 3','Revolute 4']
    right_wheel_names: ['Revolute 5','Revolute 2']

    wheel_separation: 0.186
    wheel_radius: 0.07

    use_stamped_vel: false